refresh the icon design of control panel/RunBox/eventViewer/ResourceM…
IviriusCommunity/Rebound pull request #89
Opened 2024-10-21 14:19 UTC by Shomnipotence

![image](https://github.com/user-attachments/assets/45dd8b62-aa08-4096-9a22-ce6315db65b8)

2024-10-21 14:55 UTC, jarno9981 commented
Looks good but waiting for @IviriusMain the comment about it

2024-10-21 15:03 UTC, Lamparter requested changes

2024-10-21 15:03 UTC, Lamparter commented on Delivery/AppRT/Products/Associated/RunBox.ico
Why did you delete the `.ico` files? They are used.

2024-10-21 15:03 UTC, Lamparter commented on Delivery/AppRT/Products/Associated/rcontrol.ico
> Why did you delete the `.ico` files? They are used.

Same here.

2024-10-21 15:08 UTC, Shomnipotence commented on Delivery/AppRT/Products/Associated/rcontrol.ico
They are replaced by another ico file with the same name

2024-10-21 15:08 UTC, Shomnipotence commented on Delivery/AppRT/Products/Associated/RunBox.ico
They are replaced by another ico file with the same name

2024-10-21 15:21 UTC, jarno9981 commented on Delivery/AppRT/Products/Associated/RunBox.ico
No .ico files

2024-10-21 15:26 UTC, Lamparter commented on Delivery/AppRT/Products/Associated/RunBox.ico
Oops! I didn't realise. Sorry!

2024-10-24 09:58 UTC, merged

2024-10-24 12:22 UTC, Lamparter commented
@IviriusMain seriously? That's not how PRs work. Reverting.

2024-10-24 12:25 UTC, Lamparter commented
NEVER merge without a PR approval.